config/routes.rb
Rails.application.routes.draw do
  resources :impositions, only: [:new, :create], path: ""
  resources :messages, only: [:create]

  root to: "impositions#new"
end

app/models/imposition.rb
require 'mandrill'

class Imposition < ActiveRecord::Base
  belongs_to :message

  serialize :metadata, JSON

  def notify!
    Light.alert!

    from = contact.present? ? contact : "someone"
    text = "You've received a complaint from #{from}. Hopefully the lights already flashed, but I'm sending this email just in case. You should do something."
    text += "\n#{body}" if body.present?

    Mandrill::API.new.messages.send(
      subject: "Keep It Down!",
      from_name: "Aziz",
      from_email: "aziz@jdabbs.com",
      to: [ { email: "jamesdabbs@gmail.com", name: "James Dabbs" } ],
      text: text
    )
  end
end

app/models/light.rb
class Light
  include HTTParty
  base_uri "https://www.meethue.com/api"
  default_params token: ENV.fetch("HUE_ACCESS_TOKEN")

  def self.alert!
    call "PUT", "groups/0/action", '{"on":true, "sat":255, "hue":0}'
  end

  private

  def self.call method, endpoint, message
    clip = %|clipmessage={
      bridgeId: "#{ENV.fetch 'HUE_BRIDGE_ID'}",
      clipCommand: {
        url: "/api/0/#{endpoint}",
        method: "#{method}",
        body: #{message}
      }
    }|

    post "/sendmessage", body: clip.squish, verify: false
  end
end

app/models/message.rb
class Message < ActiveRecord::Base
  has_one :imposition

  def reply text
    twilio.messages.create(
      from: ENV.fetch("TWILIO_NUMBER"),
      to:   self.from,
      body: text
    )
  end

  private

  def twilio
    @_twilio ||= Twilio::REST::Client.new(
      ENV.fetch("TWILIO_ACCOUNT_SID"),
      ENV.fetch("TWILIO_AUTH_TOKEN")
    ).account
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/impositions_controller.rb
class ImpositionsController < ApplicationController
  def new
    @imposition = Imposition.new
  end

  def create
    @imposition = Imposition.create! create_params.merge(metadata: request_metadata)
    @imposition.notify!
    head :no_content
  end

  private

  def create_params
    params.require(:imposition).permit(:contact, :body)
  end

  def request_metadata
    {
      ip:         request.remote_ip,
      user_agent: request.user_agent
    }
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  skip_before_filter :verify_authenticity_token

  def create
    if params[:AccountSid] != ENV.fetch("TWILIO_ACCOUNT_SID")
      raise "Unexpected message sender"
    end

    message = Message.create!(
      from: params[:From],
      body: params[:Body]
    )

    imposition = Imposition.create!(
      message: message,
      contact: params[:From],
      body:    params[:Body]
    ).notify!

    message.reply "Roger! Keeping it down momentarily ..."

    head :no_content
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/impositions/new.html.slim
= form_for @imposition, html: { class: "jumbotron" } do |f|
  h1 Sorry!
  p
    | I didn't mean to bother you; please let me know how I can do better:
    small.pull-right All fields optional

  .form-group
    = f.text_field :contact, class: "form-control", placeholder: "Contact information (email, phone or apt. #)"

  .form-group
    = f.text_field :body, class: "form-control", placeholder: "Requests / comments / suggestions?"

  button.btn.btn-danger.btn-lg Stop!

javascript:
  $(function() {
    var form = $("#new_imposition")
      , button = form.find("button")
      , restoreButton = function() {
        button.html(button.data("original")).removeAttr("disabled");
      };

    button.data("original", button.html());

    form.submit(function(e) {
      e.preventDefault();
      button.html("Sending ...").attr("disabled", "disabled");

      $.ajax("#{impositions_path}", {
        data:    form.serialize(),
        method:  "POST",
        success: function() {
          $("#success-modal").modal();
          restoreButton();
        },
        error: function() {
          $("#error-modal").modal();
          restoreButton();
        },
      });
    });
  });

#success-modal.modal.fade
  .modal-dialog
    .modal-content
      .modal-header
        button.close(type="button" data-dismiss="modal" aria-hidden="true") &times;
        h2 Got It!
      .modal-body
        p Assuming all goes well, my lights should be turning red in a second, and I'll cut out all the racket.

        h4 Still Being Noisy?
        It may take a few seconds for the lights to trigger, but if it's been more than a minute and nothing has happened, then something probably went wrong. Please contact me so that I can figure out what and fix it.

        h4 Questions or Suggestions?
        p If you have any questions or if there's anything I can do to help at all, please get in touch and let me know.

        br
        h4.pull-right &mdash; <i>James</i>
      .modal-footer
        ul
          li <a href="mailto:jamesdabbs@gmail.com">jamesdabbs@gmail.com</a> <i class="glyphicon glyphicon-envelope"></i>
          li 706.402.4836 <i class="glyphicon glyphicon-earphone"></i>
          li Apt #312 <i class="glyphicon glyphicon-home"></i>

#error-modal.modal.fade
  .modal-dialog
    .modal-content
      .modal-header
        button.close(type="button" data-dismiss="modal" aria-hidden="true") &times;
        h2 Uh Oh ...
      .modal-body
        p Something went wrong when trying to change the lights. Please get in touch with me, so that I can fix it (and bear with me for now - my headphones are probably on, so it may take me a bit to get back to you).
        p Thanks for your understanding.

        br
        h4.pull-right &mdash; <i>James</i>
      .modal-footer
        ul
          li <a href="mailto:jamesdabbs@gmail.com">jamesdabbs@gmail.com</a> <i class="glyphicon glyphicon-envelope"></i>
          li 706.402.4836 <i class="glyphicon glyphicon-earphone"></i>
          li Apt #312 <i class="glyphicon glyphicon-home"></i>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Lights | jdabbs.com</title>
  <%= stylesheet_link_tag '//netdna.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap.min.css' %>
  <%= stylesheet_link_tag 'application', media: 'all' %>

  <%= javascript_include_tag '//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js' %>
  <%= javascript_include_tag '//netdna.bootstrapcdn.com/bootstrap/3.0.3/js/bootstrap.min.js' %>
  <%= javascript_include_tag 'application' %>

  <%= csrf_meta_tags %>
</head>
<body>

<div class="container">
  <div class="no-js alert alert-danger">
    <h2><i class="glyphicon glyphicon-remove-sign"></i> Uh-oh ...</h2>
    <p>This app needs javascript enabled to work correctly. See <a href="http://enable-javascript.com/">this page</a> for more info.</p>
  </div>

  <%= yield %>
</div>

</body>
</html>